name: merge-dev

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'push label' }}
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Fetch PR Branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:pr-branch

      - name: Hard reset  dev to PR branch
        run: |
          git reset --hard pr-branch

      - name: Push changes to dev
        run: |
          git push origin dev --force

